=== DanTheBot827/bsqmods/source/shared/schemas/Mod.schema.base.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Mod.schema.base.json",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": ["string", "null"]
    },
    "id": {
      "type": "string"
    },
    "version": {
      "type": "string",
      "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
      "flags": "i"
    },
    "author": {
      "type": ["string", "null"]
    },
    "authorIcon": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "modloader": {
      "type": "string",
      "enum": ["QuestLoader", "Scotland2"]
    },
    "download": {
      "type": "string",
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": { "type": "string" },
          "version": { "type": "string" }
        },
        "required": ["id", "version"],
        "additionalProperties": false
      }
    },
    "source": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "cover": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*\\.(gif|jpg|jpeg|png)$",
      "flags": "i"
    },
    "funding": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri",
        "pattern": "^(http|https)://.*$",
        "flags": "i"
      }
    },
    "website": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    }
  },
  "required": ["name", "description", "id", "version", "author", "authorIcon", "modloader", "download", "dependencies", "source", "cover", "funding", "website"]
}

=== DanTheBot827/bsqmods/mods/1.13.2/qounters-minus-1.0.2.json
{
  "name": "Qounters-",
  "description": "Store brand version of Counters+ for the Quest version of Beat Saber. Adds a variety of configurable Qounters to display statistics in-game.",
  "id": "qounters-minus",
  "version": "1.0.2",
  "author": "Metalit,  danrouse",
  "authorIcon": "https://avatars.githubusercontent.com/u/128349?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/danrouse/bsq-qounters-minus/releases/download/1.0.2/qounters-minus_v1.0.2.zip",
  "dependencies": [],
  "source": "https://github.com/danrouse/bsq-qounters-minus/",
  "cover": "https://raw.githubusercontent.com/danrouse/bsq-qounters-minus/master/cover.png",
  "funding": [],
  "website": null
}

=== DanTheBot827/bsqmods/mods/1.20.0/ThiccSaber-1.1.0.json
{
  "name": "Thicc Saber",
  "description": "A simple mod which allows you to control the dimensions of notes!",
  "id": "ThiccSaber",
  "version": "1.1.0",
  "author": "Bobby Shmurner",
  "authorIcon": "https://avatars.githubusercontent.com/u/34596112?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/BobbyShmurner/ThiccSaber/releases/download/v1.1.0/Thicc_Saber-v1.1.0.qmod",
  "dependencies": [
    {
      "id": "codegen",
      "version": "^0.21.0"
    },
    {
      "id": "custom-types",
      "version": "^0.15.0"
    },
    {
      "id": "questui",
      "version": "^0.13.0"
    }
  ],
  "source": "https://github.com/BobbyShmurner/ThiccSaber/",
  "cover": "https://raw.githubusercontent.com/BobbyShmurner/ThiccSaber/master/cover.png",
  "funding": [],
  "website": null
}

=== DanTheBot827/bsqmods/mods/1.37.0_9064817954/chatui-0.1.0.json
{
  "name": "ChatUI",
  "description": "Shows your Twitch Chat Ingame",
  "id": "chatui",
  "version": "0.1.0",
  "author": "laynia_x",
  "authorIcon": "https://avatars.githubusercontent.com/u/170962081?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/vcmikuu/U-ChatUI/releases/download/0.1.0/ChatUI-0.1.0.qmod",
  "dependencies": [
    {
      "id": "bsml",
      "version": "^0.4.29"
    },
    {
      "id": "custom-types",
      "version": "^0.17.7"
    },
    {
      "id": "paper",
      "version": "^3.6.3"
    }
  ],
  "source": "https://github.com/vcmikuu/U-ChatUI/",
  "cover": "https://raw.githubusercontent.com/vcmikuu/U-ChatUI/main/cover.jpg",
  "funding": [],
  "website": "https://github.com/vcmikuu/U-ChatUI/"
}

=== DanTheBot827/bsqmods/mods/1.27.0_3631150051/chatui-0.2.11.json
{
  "name": "ChatUI",
  "description": "Shows your Twitch Chat Ingame",
  "id": "chatui",
  "version": "0.2.11",
  "author": "darknight1050",
  "authorIcon": "https://avatars.githubusercontent.com/u/18632205?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/darknight1050/ChatUI/releases/download/v0.2.11/ChatUI.qmod",
  "dependencies": [
    {
      "id": "codegen",
      "version": "^0.32.0"
    },
    {
      "id": "custom-types",
      "version": "^0.15.22"
    },
    {
      "id": "questui",
      "version": "^0.17.10"
    }
  ],
  "source": "https://github.com/darknight1050/ChatUI/",
  "cover": "https://raw.githubusercontent.com/darknight1050/ChatUI/master/cover.png",
  "funding": [],
  "website": null
}

=== DanTheBot827/bsqmods/mods/1.21.0/CrashMod-0.7.1.json
{
  "name": "CrashMod",
  "description": "Crash your game if you are bad and good\nFeatures:\n- Crash your mod via various triggers. e. g. Crash on Play, Miss, Good cut, Turn and way more",
  "id": "CrashMod",
  "version": "0.7.1",
  "author": "ComputerElite",
  "authorIcon": "https://avatars.githubusercontent.com/u/71177995?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/ComputerElite/CrashMod/releases/download/0.7.1/CrashMod.qmod",
  "dependencies": [],
  "source": "https://github.com/ComputerElite/CrashMod/",
  "cover": "https://raw.githubusercontent.com/ComputerElite/CrashMod/main/cover.png",
  "funding": [],
  "website": null
}

=== DanTheBot827/bsqmods/mods/1.24.1/songdownloader-0.4.13.json
{
  "name": "SongDownloader",
  "description": "Download Custom Songs at Runtime",
  "id": "songdownloader",
  "version": "0.4.13",
  "author": "darknight1050, EnderdracheLP, Metalit",
  "authorIcon": "https://avatars.githubusercontent.com/u/18632205?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/darknight1050/SongDownloader/releases/download/v0.4.13/SongDownloader.qmod",
  "dependencies": [
    {
      "id": "codegen",
      "version": "^0.26.2"
    },
    {
      "id": "custom-types",
      "version": "^0.15.21"
    },
    {
      "id": "questui",
      "version": "^0.16.7"
    },
    {
      "id": "songloader",
      "version": "^0.10.6"
    }
  ],
  "source": "https://github.com/darknight1050/SongDownloader/",
  "cover": "https://raw.githubusercontent.com/darknight1050/SongDownloader/master/cover.png",
  "funding": [],
  "website": "https://github.com/darknight1050/SongDownloader/"
}

=== DanTheBot827/bsqmods/mods/1.37.0_9064817954/qbeatsaberplus-notetweaker-6.3.2.json
{
  "name": "QBeatSaberPlus-NoteTweaker",
  "description": "Feel good!",
  "id": "qbeatsaberplus-notetweaker",
  "version": "6.3.2",
  "author": "HardCPP",
  "authorIcon": "https://avatars.githubusercontent.com/u/2964819?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/hardcpp/QBeatSaberPlus-NoteTweaker/releases/download/v6.3.2/QBeatSaberPlus-NoteTweaker.qmod",
  "dependencies": [
    {
      "id": "chatplex-sdk-bs",
      "version": "^6.3.2"
    },
    {
      "id": "custom-types",
      "version": "^0.17.8"
    },
    {
      "id": "paper",
      "version": "^3.6.3"
    }
  ],
  "source": "https://github.com/hardcpp/QBeatSaberPlus-NoteTweaker/",
  "cover": "https://raw.githubusercontent.com/hardcpp/QBeatSaberPlus-NoteTweaker/master/cover.png",
  "funding": [],
  "website": "https://github.com/hardcpp/QBeatSaberPlus-NoteTweaker/"
}

=== DanTheBot827/bsqmods/mods/1.40.7_7060/metacore-1.3.3.json
{
  "name": "MetaCore",
  "description": "Provides way too many utilities for mod developers",
  "id": "metacore",
  "version": "1.3.3",
  "author": "Metalit",
  "authorIcon": "https://avatars.githubusercontent.com/u/48568911?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/Metalit/MetaCore/releases/download/v1.3.3/MetaCore.qmod",
  "dependencies": [
    {
      "id": "beatsaber-hook",
      "version": "^6.4.2"
    },
    {
      "id": "custom-types",
      "version": "^0.18.3"
    },
    {
      "id": "paper2_scotland2",
      "version": "^4.6.4"
    },
    {
      "id": "song-details",
      "version": "^1.0.3"
    },
    {
      "id": "web-utils",
      "version": "^0.6.7"
    }
  ],
  "source": "https://github.com/Metalit/MetaCore/",
  "cover": null,
  "funding": [],
  "website": "https://github.com/Metalit/MetaCore/"
}
