=== DanTheBot827/bsqmods/source/shared/schemas/Mod.schema.base.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Mod.schema.base.json",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": ["string", "null"]
    },
    "id": {
      "type": "string"
    },
    "version": {
      "type": "string",
      "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
      "flags": "i"
    },
    "author": {
      "type": ["string", "null"]
    },
    "authorIcon": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "modloader": {
      "type": "string",
      "enum": ["QuestLoader", "Scotland2"]
    },
    "download": {
      "type": "string",
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": { "type": "string" },
          "version": { "type": "string" }
        },
        "required": ["id", "version"],
        "additionalProperties": false
      }
    },
    "source": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "cover": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*\\.(gif|jpg|jpeg|png)$",
      "flags": "i"
    },
    "funding": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri",
        "pattern": "^(http|https)://.*$",
        "flags": "i"
      }
    },
    "website": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    }
  },
  "required": ["name", "description", "id", "version", "author", "authorIcon", "modloader", "download", "dependencies", "source", "cover", "funding", "website"]
}

=== DanTheBot827/bsqmods/mods/1.25.1/vent-1.0.0.json
{
  "name": "Vent",
  "description": "I swear you just vented...",
  "id": "vent",
  "version": "1.0.0",
  "author": "IMB11 (IMB11)",
  "authorIcon": "https://avatars.githubusercontent.com/u/93472213?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/IMB11/Vent/releases/download/1.0.0/Vent-1.0.0%2B1251.qmod",
  "dependencies": [
    {
      "id": "codegen",
      "version": "^0.28.0"
    },
    {
      "id": "custom-types",
      "version": "^0.15.22"
    },
    {
      "id": "questui",
      "version": "*"
    }
  ],
  "source": "https://github.com/IMB11/Vent/",
  "cover": "https://raw.githubusercontent.com/IMB11/Vent/master/cover.png",
  "funding": [],
  "website": null
}

=== DanTheBot827/bsqmods/mods/1.26.2/multiplayer-core-1.3.4.json
{
  "name": "MultiplayerCore",
  "description": "Port of MultiplayerCore, the PC mod that adds features to BeatTogether Multiplayer.",
  "id": "multiplayer-core",
  "version": "1.3.4",
  "author": "Goobie",
  "authorIcon": "https://avatars.githubusercontent.com/u/81266776?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/EnderdracheLP/MultiplayerCore.Quest/releases/download/1.3.4/MultiplayerCore_1.3.4.qmod",
  "dependencies": [
    {
      "id": "BeatTogether",
      "version": "^1.7.1"
    },
    {
      "id": "codegen",
      "version": "^0.31.0"
    },
    {
      "id": "custom-types",
      "version": "^0.15.22"
    },
    {
      "id": "pinkcore",
      "version": "^1.8.6"
    },
    {
      "id": "questui",
      "version": "^0.17.9"
    },
    {
      "id": "songdownloader",
      "version": "^0.5.4"
    },
    {
      "id": "songloader",
      "version": "^0.10.12"
    }
  ],
  "source": "https://github.com/EnderdracheLP/MultiplayerCore.Quest/",
  "cover": "https://raw.githubusercontent.com/EnderdracheLP/MultiplayerCore.Quest/master/Cover.png",
  "funding": [],
  "website": null
}

=== DanTheBot827/bsqmods/mods/1.26.0/mod-list-0.1.8.json
{
  "name": "ModList",
  "description": "Displays your installed mods inside the game and gives you a warning prompt upon starting the game to tell you if a mod failed to load.",
  "id": "mod-list",
  "version": "0.1.8",
  "author": "Lauriethefish",
  "authorIcon": "https://avatars.githubusercontent.com/u/44222319?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/Lauriethefish/ModList/releases/download/v0.1.8/ModList.qmod",
  "dependencies": [
    {
      "id": "codegen",
      "version": "^0.29.0"
    },
    {
      "id": "custom-types",
      "version": "^0.15.22"
    },
    {
      "id": "questui",
      "version": "^0.17.6"
    }
  ],
  "source": "https://github.com/Lauriethefish/ModList/",
  "cover": "https://raw.githubusercontent.com/Lauriethefish/ModList/main/cover.png",
  "funding": [],
  "website": null
}

=== DanTheBot827/bsqmods/mods/1.17.1/codegen-0.14.0.json
{
  "name": "Codegen",
  "description": null,
  "id": "codegen",
  "version": "0.14.0",
  "author": "Sc2ad",
  "authorIcon": "https://avatars.githubusercontent.com/u/10663758?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/sc2ad/BeatSaber-Quest-Codegen/releases/download/v0.14.0/codegen_0_14_0.qmod",
  "dependencies": [],
  "source": "https://github.com/sc2ad/BeatSaber-Quest-Codegen/",
  "cover": "https://raw.githubusercontent.com/sc2ad/BeatSaber-Quest-Codegen/master/cover.png",
  "funding": [],
  "website": null
}

=== DanTheBot827/bsqmods/mods/1.28.0_4124311467/qbeatsaberplus-gametweaker-1.0.0-v6.2.0.json
{
  "name": "QBeatSaberPlus-GameTweaker",
  "description": "Feel good!",
  "id": "qbeatsaberplus-gametweaker",
  "version": "1.0.0-v6.2.0",
  "author": "HardCPP",
  "authorIcon": "https://avatars.githubusercontent.com/u/2964819?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/hardcpp/QBeatSaberPlus-GameTweaker/releases/download/v1.0.0-v6.2.0/QBeatSaberPlus-GameTweaker.qmod",
  "dependencies": [
    {
      "id": "chatplex-sdk-bs",
      "version": "^1.0.0-v6.2.0"
    },
    {
      "id": "codegen",
      "version": "^0.33.0"
    },
    {
      "id": "custom-types",
      "version": "^0.15.24"
    },
    {
      "id": "songloader",
      "version": "^0.10.15"
    }
  ],
  "source": "https://github.com/hardcpp/QBeatSaberPlus-GameTweaker/",
  "cover": "https://raw.githubusercontent.com/hardcpp/QBeatSaberPlus-GameTweaker/master/cover.png",
  "funding": [],
  "website": "https://github.com/hardcpp/QBeatSaberPlus-GameTweaker/"
}

=== DanTheBot827/bsqmods/mods/1.37.0_9064817954/SmallQubes-0.3.1.json
{
  "name": "SmallQubes",
  "description": "Adds a slider to change default cubes size",
  "id": "SmallQubes",
  "version": "0.3.1",
  "author": "NSGolova",
  "authorIcon": "https://avatars.githubusercontent.com/u/8793817?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/NSGolova/SmallQubes/releases/download/v0.3.1/SmallQubes.qmod",
  "dependencies": [
    {
      "id": "bsml",
      "version": "^0.4.34"
    },
    {
      "id": "custom-types",
      "version": "^0.17.8"
    },
    {
      "id": "paper",
      "version": "^3.6.3"
    }
  ],
  "source": "https://github.com/NSGolova/SmallQubes/",
  "cover": "https://raw.githubusercontent.com/NSGolova/SmallQubes/master/cover.png",
  "funding": [],
  "website": null
}

=== DanTheBot827/bsqmods/mods/1.24.0/SmallQubes-0.1.0.json
{
  "name": "SmallQubes",
  "description": null,
  "id": "SmallQubes",
  "version": "0.1.0",
  "author": "NSGolova",
  "authorIcon": "https://avatars.githubusercontent.com/u/8793817?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/NSGolova/SmallQubes/releases/download/v0.1.0/SmallQubes.qmod",
  "dependencies": [
    {
      "id": "codegen",
      "version": "^0.25.0"
    },
    {
      "id": "custom-types",
      "version": "^0.15.13"
    },
    {
      "id": "questui",
      "version": "^0.16.1"
    }
  ],
  "source": "https://github.com/NSGolova/SmallQubes/",
  "cover": "https://raw.githubusercontent.com/NSGolova/SmallQubes/master/cover.png",
  "funding": [],
  "website": null
}

=== DanTheBot827/bsqmods/mods/1.40.5_5928/DlcSorter-0.1.10.json
{
  "name": "DlcSorter",
  "description": "Sorts the DLC packs alphabetically.",
  "id": "DlcSorter",
  "version": "0.1.10",
  "author": "DanTheMan827",
  "authorIcon": "https://avatars.githubusercontent.com/u/176073241?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/DanTheMan827-BeatSaber/Quest.DlcSorter/releases/download/v0.1.10/DlcSorter.qmod",
  "dependencies": [
    {
      "id": "beatsaber-hook",
      "version": "^6.4.1"
    },
    {
      "id": "paper2_scotland2",
      "version": "^4.6.1"
    }
  ],
  "source": "https://github.com/DanTheMan827-BeatSaber/Quest.DlcSorter/",
  "cover": "https://raw.githubusercontent.com/DanTheMan827-BeatSaber/Quest.DlcSorter/master/cover.png",
  "funding": [],
  "website": "https://github.com/DanTheMan827-BeatSaber/Quest.DlcSorter/"
}
