=== DanTheBot827/bsqmods/source/shared/schemas/Mod.schema.base.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Mod.schema.base.json",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": ["string", "null"]
    },
    "id": {
      "type": "string"
    },
    "version": {
      "type": "string",
      "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
      "flags": "i"
    },
    "author": {
      "type": ["string", "null"]
    },
    "authorIcon": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "modloader": {
      "type": "string",
      "enum": ["QuestLoader", "Scotland2"]
    },
    "download": {
      "type": "string",
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": { "type": "string" },
          "version": { "type": "string" }
        },
        "required": ["id", "version"],
        "additionalProperties": false
      }
    },
    "source": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "cover": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*\\.(gif|jpg|jpeg|png)$",
      "flags": "i"
    },
    "funding": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri",
        "pattern": "^(http|https)://.*$",
        "flags": "i"
      }
    },
    "website": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    }
  },
  "required": ["name", "description", "id", "version", "author", "authorIcon", "modloader", "download", "dependencies", "source", "cover", "funding", "website"]
}

=== DanTheBot827/bsqmods/mods/1.27.0_3631150051/BSNightcoreQuest-0.1.0.json
{
  "name": "BSNightcoreQuest",
  "description": "Removes pitch compensation to make songs go nightcore on different speed",
  "id": "BSNightcoreQuest",
  "version": "0.1.0",
  "author": "Tatenshi",
  "authorIcon": "https://avatars.githubusercontent.com/u/55283269?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/Tatenshi/BSNightcoreQuest/releases/download/v0.1.0/BSNightcoreQuest_1_27_0.qmod",
  "dependencies": [
    {
      "id": "codegen",
      "version": "=0.32.0"
    },
    {
      "id": "custom-types",
      "version": "^0.15.22"
    },
    {
      "id": "questui",
      "version": "^0.17.10"
    }
  ],
  "source": "https://github.com/Tatenshi/BSNightcoreQuest/",
  "cover": null,
  "funding": [],
  "website": null
}

=== DanTheBot827/bsqmods/mods/1.24.0/RedBar-1.10.0.json
{
  "name": "RedBar",
  "description": "Change the color of your health bar according to your health\n\nFeatures:\n- Custom color for your energy bar which changes according to your health\n- Rainbow mode",
  "id": "RedBar",
  "version": "1.10.0",
  "author": "ComputerElite",
  "authorIcon": "https://avatars.githubusercontent.com/u/71177995?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/ComputerElite/RedBar/releases/download/1.10.0/RedBar.qmod",
  "dependencies": [
    {
      "id": "codegen",
      "version": "^0.25.0"
    },
    {
      "id": "custom-types",
      "version": "^0.15.18"
    },
    {
      "id": "questui",
      "version": "^0.16.2"
    }
  ],
  "source": "https://github.com/ComputerElite/RedBar/",
  "cover": "https://raw.githubusercontent.com/ComputerElite/RedBar/master/cover.png",
  "funding": [],
  "website": null
}

=== DanTheBot827/bsqmods/mods/1.34.2_7115288407/safestorage-1.1.1.json
{
  "name": "SafeStorage",
  "description": "Allows for safe storage and encryption of strings to prevent users from accidentally doxxing themselves",
  "id": "safestorage",
  "version": "1.1.1",
  "author": "hdgamer1404Jonas",
  "authorIcon": "https://avatars.githubusercontent.com/u/65252066?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/jxnxsdev/SafeStorage/releases/download/v1.1.1/SafeStorage.qmod",
  "dependencies": [],
  "source": "https://github.com/jxnxsdev/SafeStorage/",
  "cover": null,
  "funding": [],
  "website": "https://github.com/jxnxsdev/SafeStorage/"
}

=== DanTheBot827/bsqmods/mods/1.13.0/BeatTogether-1.0.1.json
{
  "name": "BeatTogether",
  "description": "A multiplayer private server for the modding community. Supports crossplay between PC and Quest.",
  "id": "BeatTogether",
  "version": "1.0.1",
  "author": "BeatTogether Team",
  "authorIcon": "https://avatars.githubusercontent.com/u/9069824?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/BeatTogether/BeatTogether.Quest/releases/download/v1.0.1/BeatTogether_v1.0.1.zip",
  "dependencies": [],
  "source": "https://github.com/BeatTogether/BeatTogether.Quest/",
  "cover": "https://raw.githubusercontent.com/BeatTogether/BeatTogether.Quest/master/Cover.png",
  "funding": [],
  "website": null
}

=== DanTheBot827/bsqmods/mods/1.37.0_9064817954/anytext-1.0.1.json
{
  "name": "AnyText",
  "description": "Change any text in the game",
  "id": "anytext",
  "version": "1.0.1",
  "author": "CatsaCode",
  "authorIcon": "https://avatars.githubusercontent.com/u/155121307?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/CatsaCode/AnyText/releases/download/v1.0.1-bs-1.37.0/AnyText.qmod",
  "dependencies": [
    {
      "id": "bsml",
      "version": "^0.4.43"
    },
    {
      "id": "custom-types",
      "version": "^0.17.10"
    },
    {
      "id": "paper",
      "version": "^3.0.0"
    }
  ],
  "source": "https://github.com/CatsaCode/AnyText/",
  "cover": "https://raw.githubusercontent.com/CatsaCode/AnyText/main/cover.png",
  "funding": [],
  "website": "https://github.com/CatsaCode/AnyText/"
}

=== DanTheBot827/bsqmods/mods/1.40.8_7379/too-many-fireworks-1.2.5.json
{
  "name": "TooManyFireworks",
  "description": "Don't think there's enough fireworks? This mod adds a variety of settings that can make fireworks powerful enough to explode the game itself!",
  "id": "too-many-fireworks",
  "version": "1.2.5",
  "author": "CatsaCode",
  "authorIcon": "https://avatars.githubusercontent.com/u/155121307?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/CatsaCode/TooManyFireworks/releases/download/v1.2.5/TooManyFireworks.qmod",
  "dependencies": [
    {
      "id": "beatsaber-hook",
      "version": "^6.4.2"
    },
    {
      "id": "bsml",
      "version": "^0.4.55"
    },
    {
      "id": "custom-types",
      "version": "^0.18.3"
    },
    {
      "id": "paper2_scotland2",
      "version": "^4.6.4"
    }
  ],
  "source": "https://github.com/CatsaCode/TooManyFireworks/",
  "cover": "https://raw.githubusercontent.com/CatsaCode/TooManyFireworks/main/cover.png",
  "funding": [],
  "website": "https://github.com/CatsaCode/TooManyFireworks/"
}

=== DanTheBot827/bsqmods/mods/1.13.0/AntiVertigo-1.0.0.json
{
  "name": "AntiVertigo",
  "description": "Spawns a plane or circle under you to help you deal with vertigo issues.",
  "id": "AntiVertigo",
  "version": "1.0.0",
  "author": "RedBrumbler",
  "authorIcon": "https://avatars.githubusercontent.com/u/51795403?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/RedBrumbler/AntiVertigo/releases/download/1.0.0/AntiVertigo.zip",
  "dependencies": [],
  "source": "https://github.com/RedBrumbler/AntiVertigo/",
  "cover": "https://raw.githubusercontent.com/RedBrumbler/AntiVertigo/master/cover.png",
  "funding": [],
  "website": null
}

=== DanTheBot827/bsqmods/mods/1.28.0_4124311467/leaderboardcore-0.0.3.json
{
  "name": "LeaderboardCore",
  "description": "Adds the capability to add custom leaderboards to Beat Saber with relative ease!",
  "id": "leaderboardcore",
  "version": "0.0.3",
  "author": "Raine, RedBrumbler",
  "authorIcon": "https://avatars.githubusercontent.com/u/64136899?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/raineaeternal/LeaderboardCore/releases/download/v0.0.3/LeaderboardCore.qmod",
  "dependencies": [
    {
      "id": "bsml",
      "version": "^0.3.1"
    },
    {
      "id": "codegen",
      "version": "^0.33.0"
    },
    {
      "id": "custom-types",
      "version": "^0.15.23"
    },
    {
      "id": "lapiz",
      "version": "^0.1.11"
    },
    {
      "id": "paper",
      "version": "^1.2.9"
    }
  ],
  "source": "https://github.com/raineaeternal/LeaderboardCore/",
  "cover": null,
  "funding": [],
  "website": "https://github.com/raineaeternal/LeaderboardCore/"
}
